---
name: on pull_request

"on":
  pull_request:

jobs:
  test:
    name: Test
    permissions:
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Rust 1.98.1 をインストール
        run: rustup toolchain install 1.98.1 --profile minimal
      - name: テストを実行
        run: cargo +1.98.1 test --locked
