---
name: on pull_request

"on":
  pull_request:

jobs:
  test:
    name: Test
    permissions:
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - name: コードをチェックアウト
        # actions/checkout v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Cargo.toml からRustの版を取得
        run: |
          rust_version="$(cargo metadata --no-deps --format-version=1 |
            jq -er --arg manifest_path "$GITHUB_WORKSPACE/Cargo.toml" \
              '.packages[] |
              select(.manifest_path == $manifest_path) |
              .rust_version')"
          printf 'RUST_VERSION=%s\n' "$rust_version" >> "$GITHUB_ENV"
      - name: Rustをインストール
        run: rustup toolchain install "$RUST_VERSION" --profile minimal
      - name: テストを実行
        run: cargo +"$RUST_VERSION" test --locked
